# AWS
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_SESSION_TOKEN=IQoJb3JpZ2luX2VjEKP//////////wEaCXVzLWVhc3QtMSJGMEQCIH...

# Stripe
STRIPE_SECRET_KEY=sk_test_51Hh1q2EXAMPLEy3A6SjKgzpR9W
STRIPE_PUBLISHABLE_KEY=pk_test_51Hh1q2EXAMPLE5jN3L2bq

# Jira
JIRA_API_TOKEN=ATATT3xFfGF0EXAMPLEyNfM4HzsK9QJ
JIRA_USERNAME=example.user@domain.com
JIRA_BASE_URL=https://example.atlassian.net

# GCP
GCP_PROJECT_ID=my-demo-project-12345
GCP_CLIENT_EMAIL=fake-service-account@my-demo-project-12345.iam.gserviceaccount.com
GCP_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0B...FAKE...\n-----END PRIVATE KEY-----\n

# GitHub
GITHUB_TOKEN=ghp_SkcaJ9ksKtU28f4mWIYPG9DdOGimlq4cUBgA

# Slack
SLACK_BOT_TOKEN=xoxb-123456789012-1234567890123-ABCDEFGHIJKLMNopqrstuvwxyz
SLACK_SIGNING_SECRET=8f742231b10e8888abcd99yyyzzz85a5

# Twilio
TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
TWILIO_AUTH_TOKEN=your_auth_token_here
